language: c
os: linux
compiler: gcc

addons:
    apt:
        packages:
            - cmake
            - valgrind

env:
    - DIR=iz_1

install:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    
before_script:
    - cd $DIR
    - cmake .
    - make
    - ls

script:
    - valgrind --leak-check=full -q ./untitled.a < test.txt
    - ./untitled.a

after_script:
    - make clean
