language: c
os: linux
compiler: gcc

addons:
    apt:
        packages:
            - cmake
            - valgrind

env:
    - DIR=iz_1

install:
    - ls
    - cd /usr/src/
    - sudo cmake CMakeLists.txt || (cat CMakeFiles/CMakeError.log && CMakeFiles/CMakeOutput.log)
    - sudo make
    - sudo cp *.a /iz_1
    - cd -
    
before_script:
    - cd $DIR
    - cmake .
    - make
    - ls

script:
    - valgrind --leak-check=full -q ./untitled.a < test.txt
    - ./untitled.a

after_script:
    - make clean
